### ISSUE TITLE
Missing English Translation

### ISSUE THREAD

**Issue by chickensmitten** [fulcrum-agile/fulcrum#242]
Hi, I am new to Ruby and Rails. 

Manage to setup Fulcrum locally and in Heroku. While the local fulcrum has no issues, the one deployed to Heroku has issue with english translation for labels. i.e. [missing "en.velocity" translation]

Googled and only found one possible lead, https://github.com/fulcrum-agile/fulcrum/issues/226
Followed it, but the problem persist. 

Is there something I am missing?

**Comment by malclocke** [comment]
Closed by #235
